name: 'Release PDF'

on:
  workflow_run:
    workflows: ["Build LaTex Document"]  # ✅ Must match the name in compile-latex.yml
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled PDF
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdfs
          path: ./artifact

      - name: Create or Update "latest" GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Latest Release
          tag_name: latest
          files: ./artifact/*.pdf
          make_latest: true
          body: |
            Latest PDF files.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
